openapi: 3.0.3
info:
  title: Enhanced Configuration Management Operations API
  description: Internal API contracts for backward-compatible configuration enhancements
  version: 1.0.0

paths:
  /configure/agent:
    post:
      summary: Configure agent with optional source path tracking
      operationId: configureAgentEnhanced
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, entrypoint]
              properties:
                name:
                  type: string
                  pattern: "^[a-zA-Z0-9_-]+$"
                  description: "Unique agent name"
                entrypoint:
                  type: string
                  description: "Path to agent entrypoint file"
                source_path:
                  type: string
                  description: "Optional source code directory path"
                output_directory:
                  type: string
                  description: "Custom output directory for configuration"
      responses:
        '200':
          description: Agent configured successfully with optional enhancements
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnhancedConfigurationResult'
        '400':
          description: Invalid configuration parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /launch/agent:
    post:
      summary: Launch agent with automatic build artifact organization
      operationId: launchAgentEnhanced
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [agent_name]
              properties:
                agent_name:
                  type: string
                  description: "Name of agent to launch"
      responses:
        '200':
          description: Agent launched successfully with organized build artifacts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnhancedLaunchResult'
        '400':
          description: Invalid launch parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /status/agent:
    get:
      summary: Get agent status with source path and build artifact information
      operationId: getAgentStatusEnhanced
      parameters:
        - name: agent_name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Agent status with enhanced information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnhancedAgentStatus'
        '404':
          description: Agent not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /agents:
    get:
      summary: List all agents with enhanced status information
      operationId: listAgentsEnhanced
      responses:
        '200':
          description: List of agents with enhanced information
          content:
            application/json:
              schema:
                type: object
                properties:
                  agents:
                    type: array
                    items:
                      $ref: '#/components/schemas/EnhancedAgentSummary'
                  default_agent:
                    type: string
                    nullable: true

components:
  schemas:
    EnhancedConfigurationResult:
      type: object
      properties:
        agent_name:
          type: string
        configuration_path:
          type: string
        source_path:
          type: string
          nullable: true
          description: "Tracked source path if provided"
        status:
          type: string
          enum: [configured, updated]
        backward_compatible:
          type: boolean
          description: "Whether configuration maintains backward compatibility"

    EnhancedLaunchResult:
      type: object
      properties:
        agent_arn:
          type: string
        build_artifacts:
          $ref: '#/components/schemas/BuildArtifactInfo'
        deployment_status:
          type: string
        observability_urls:
          type: object
        source_path_used:
          type: string
          nullable: true
          description: "Source path used for build"

    EnhancedAgentStatus:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
          enum: [configured, deployed, ready, error]
        entrypoint:
          type: string
        source_path:
          type: string
          nullable: true
          description: "Tracked source path"
        build_artifacts:
          $ref: '#/components/schemas/BuildArtifactInfo'
        last_modified:
          type: string
          format: date-time
        deployment_info:
          type: object
          description: "Existing deployment information"

    EnhancedAgentSummary:
      type: object
      properties:
        name:
          type: string
        entrypoint:
          type: string
        source_path:
          type: string
          nullable: true
        status:
          type: string
          enum: [configured, deployed, ready, error]
        has_build_artifacts:
          type: boolean
          description: "Whether build artifacts exist"
        last_modified:
          type: string
          format: date-time

    BuildArtifactInfo:
      type: object
      properties:
        base_directory:
          type: string
          description: "Root directory for build artifacts"
        source_copy_path:
          type: string
          description: "Path to copied source code"
        dockerfile_path:
          type: string
          description: "Path to generated Dockerfile"
        build_timestamp:
          type: string
          format: date-time
          description: "When artifacts were created"
        organized:
          type: boolean
          description: "Whether artifacts are properly organized"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        details:
          type: string
        suggestion:
          type: string
        backward_compatible:
          type: boolean
          description: "Whether error affects backward compatibility"
